#!/bin/bash

SOCK_TYPE="UNIX-CONNECT"
SOCK_PATH="/tmp/memeblink_overlay.sock"
SOCK="$SOCK_TYPE:$SOCK_PATH"

PAYLOAD="{\"image_path\": \"$1\", \"duration_ms\": 10000, \"anchor\": \"Center\", \"width\": \"auto\", \"height\": 216, \"x\": 10, \"y\": 50, \"text\": \"$2\", \"text_position\": \"above\", \"text_color\": \"#FFFFFF\", \"text_size\": 30.0}"

echo "$PAYLOAD" | socat - "$SOCK"
