#!/bin/bash

SOCK_TYPE="UNIX-CONNECT"
SOCK_PATH="/tmp/memeblink_overlay.sock"
SOCK="$SOCK_TYPE:$SOCK_PATH"

PAYLOAD="{\"image_path\": \"$1\", \"duration_ms\": $2, \"anchor\": \"$3\", \"width\": $4, \"height\": $5, \"x\": $6, \"y\": $7, \"text\": \"$8\", \"text_position\": \"$9\", \"text_color\": \"${10}\", \"text_size\": ${11}}"

echo "$PAYLOAD" | socat - "$SOCK"
